#!/usr/bin/env python3
"""Generate SVG delivery files and Flutter paths from the reviewed icon catalog.

No external packages or network requests. Run with --check in validation.
"""
import argparse
import json
import re
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ICONS = ROOT / "docs/design/icons"


def outputs():
    catalog = json.loads((ICONS / "catalog.json").read_text())
    ids, aliases = set(), set()
    generated = {}
    mappings = []
    symbols = []
    filled = []
    groups = {}
    for item in catalog:
        name, path = item["id"], item["path"]
        assert name not in ids, name
        ids.add(name)
        assert re.fullmatch(r"[MLQCZ\d.\s-]+", path), name
        for alias in item["material"]:
            assert alias not in aliases, alias
            aliases.add(alias)
            mappings.append(f"  Icons.{alias}: '{path}',")
            if item.get("paint") == "fill":
                filled.append(f"  Icons.{alias},")
        body = f'<path d="{path}"/>'
        attributes = 'fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"'
        if item.get("paint") == "fill":
            attributes = 'fill="currentColor" fill-rule="evenodd" stroke="none"'
        generated[ICONS / "svg" / f"{name}.svg"] = (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {attributes}>'
            f'<title>{escape(item["label"])}</title>{body}</svg>\n'
        )
        symbols.append(f'<symbol id="{name}" viewBox="0 0 24 24" {attributes}>{body}</symbol>')
        groups.setdefault(item["group"], []).append(item)
    sprite = '<svg xmlns="http://www.w3.org/2000/svg"><defs>' + ''.join(symbols) + '</defs></svg>\n'
    generated[ICONS / "sprite.svg"] = sprite
    generated[ROOT / "apps/supplier_app/lib/widgets/icon_paths.g.dart"] = (
        '// GENERATED by tool/generate_business_icons.py. Edit docs/design/icons/catalog.json.\n'
        "import 'package:flutter/material.dart';\n\n"
        'final businessIconPaths = Map<IconData, String>.unmodifiable({\n' + '\n'.join(mappings) + '\n});\n\n'
        'const Map<String, IconData> businessIconNames = {\n'
        + '\n'.join(f"  '{alias}': Icons.{alias}," for alias in sorted(aliases)) + '\n};\n'
        + '\nfinal businessIconFills = Set<IconData>.unmodifiable({\n' + '\n'.join(filled) + '\n});\n'
    )
    sections = []
    for group, items in groups.items():
        rows = []
        for item in items:
            name, label = item['id'], escape(item['label'])
            icon = f'<svg aria-hidden="true"><use href="#{name}"/></svg>'
            rows.append(f'<article class="glyph"><div class="pair"><span class="light">{icon}</span><span class="dark">{icon}</span></div><a href="svg/{name}.svg" download>{label}</a><small>{name}</small></article>')
        sections.append(f'<section><h2>{group} <span>{len(items)}</span></h2><div class="grid">' + ''.join(rows) + '</div></section>')
    template = (ICONS / "preview.template.html").read_text()
    generated[ICONS / "index.html"] = template.replace('{{SYMBOLS}}', ''.join(symbols)).replace('{{SECTIONS}}', ''.join(sections)).replace('{{COUNT}}', str(len(catalog)))
    admin = ROOT / "services/supplier_hub/web/index.html"
    by_id = {item['id']: item for item in catalog}
    def admin_icon(match):
        item = by_id[match.group(2)]
        paint = 'fill="currentColor" fill-rule="evenodd" stroke="none"' if item.get('paint') == 'fill' else 'fill="none" stroke="currentColor"'
        return match.group(1) + f'<path d="{item["path"]}" {paint}/></svg>'
    generated[admin] = re.sub(r'(<svg[^>]*data-icon="([^"]+)"[^>]*>).*?</svg>', admin_icon, admin.read_text())
    graph = ROOT / "apps/supplier_app/assets/ontology_graph/index.html"
    graph_text = graph.read_text()
    match = re.search(r'window\.ONTOLOGY_ASSETS=(\{.*?\});', graph_text)
    if match:
        assets = json.loads(match.group(1))
        assets['catalog'] = catalog
        encoded = json.dumps(assets, ensure_ascii=False, separators=(',', ':'))
        generated[graph] = graph_text[:match.start(1)] + encoded + graph_text[match.end(1):]
    return generated


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for file, content in outputs().items():
        if args.check:
            if not file.exists() or file.read_text() != content:
                stale.append(str(file.relative_to(ROOT)))
        else:
            file.parent.mkdir(parents=True, exist_ok=True)
            file.write_text(content)
    if stale:
        raise SystemExit('Stale generated icons: ' + ', '.join(stale))
    print('Icon artifacts are current.' if args.check else 'Generated SVG icons, comparison page, and Flutter paths.')


if __name__ == '__main__':
    main()
